# Site settings
title: Das OpenKnowledgeLab für Stadt und Region
email: datalove@uni-ulm.de
description: > # this means to ignore newlines until "baseurl:"
 Wir sind eine Gruppe von Open-Data-Interessierten aus Ulm.
 Unser Ziel ist es, gemeinsam diverse Datensätze unter offener Lizenz zu erhalten,
 anschließend per API für Drittanwendungen verfügbar zu machen und tolle Anwendungen daraus zu bauen. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ulmapi.de" # the base hostname & protocol for your site
twitter_username: ulmapi
github_username:  ulmapi

# Build settings
markdown: kramdown
